name: Docker Image CD

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ${{ secrets.WORKINGDIRECTORY }}/gradlew

    - name: Build with Gradle Wrapper
      run: ./${{ secrets.WORKINGDIRECTORY }}/gradlew clean build
      working-directory: ${{ secrets.WORKINGDIRECTORY }}

    - name: Copy JAR file to build context
      run: cp ${{ secrets.WORKINGDIRECTORY }}/build/libs/*.jar $GITHUB_WORKSPACE/

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_REPOSITORY_USERNAME }}
        password: ${{ secrets.DOCKER_REPOSITORY }}

    - name: Build and push Docker image
      run: |
        docker buildx build --push \
          --tag skyriv213/tastyhub/my-app:latest \
          --tag skyriv213/tastyhub/my-app:${{ github.sha }} \
          --file $GITHUB_WORKSPACE/Dockerfile \
          $GITHUB_WORKSPACE
