#last

name: Docker Image CD

on:
  push:
    branches: [ "dev","main" ]

#dddd
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_REPOSITORY_USERNAME }}
        password: ${{ secrets.DOCKER_REPOSITORY }}

    - name: Build frontend Docker image
      run: |
        docker build -t skyriv213/tastyhub-front -f ./fe/Dockerfile ./fe


    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.DOCKER_REPOSITORY_USERNAME }}/tastyhub-front:${{ github.sha }}, ${{ secrets.DOCKER_REPOSITORY_USERNAME }}/tastyhub-front:latest
      
